#!/usr/bin/env bash

script=$(basename $0)
namespace=$(echo ${script} | cut -d"." -f 2)
namespaceArg=""

if [ "${namespace}" != "${script}" ]
then
  namespaceArg="--namespace=${namespace}"
fi

echo "*** namespace: ${namespace}"
kubectl ${namespaceArg} $*

